public class AClass1 {
    // the 1st commit
    //   upda    ted
    // updated once again

    Integer var4 = 111;
    
    // add new line after 2 new empty lines 
    //post  sd comment
    // comment changed 234
    // comment with problem symbols '@$~56__+= '   'and 
    // new line add
    // extra line 1
    // extra line 0
    // also 1 line
    // even more lines
    //324<>ÕÄ®@£ʡʤɆڑ↨≥∑∑☺
    // the 2nd line added 1
    // ¶☼♀♂♥ⱠⱤﬡ
    // the 3rd line
    // , 梨, 阜, 埼, 茨
    // 当用漢字
    Double f1 = 0.1;
    // updated
    Integer i19 = 1000;
    // extra line 2
    // extra line 3    
    // the 1st commit 1
    //   updated 122
    public String method1(){
        return 'Ok';
    }
}