public with sharing class ClassOne 
{
    public ClassOne()
    {
        System.debug('ClassOne');
        //This method is add.
        //This method is add.
        //This method is add 1.
    }
    
    public void myMethod()
    {
        Integer ra=9;
        Integer r2=10;
        // add a line 15
        // some special ▲♣♪
    }
    
    public void unitTestMethod()
    {
        //sdfsfse//sfe
    }
}